export const ADD_CURRENCY = "ADD_CURRENCY";
export const REMOVE_CURRENCY = "REMOVE_CURRENCY";
export const POPULATE_CURRENCY = "POPULATE_CURRENCY";
export const ADD_USER_CURRENCY = "ADD_USER_CURRENCY";
export const REMOVE_USER_CURRENCY = "REMOVE_USER_CURRENCY";
export const REMOVE_USER_ALL = "REMOVE_USER_ALL";
